This line is updating in master branch...
iam updating this file in development branch.......
THis file contains all deployment scripts.............
For sv ...........
Git merge abort command use case..
Happy birthday bhavana jii...
Party leda bhavana garu...

